"""Bismillahirrahmanirrahim, non-nullable password

Revision ID: 373f26f9c4ec
Revises: 5a97cee101c6
Create Date: 2024-04-11 00:11:14.941892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373f26f9c4ec'
down_revision = '5a97cee101c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=101),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=101),
               nullable=True)

    # ### end Alembic commands ###
